
#ifndef _C1_kl3_
#define _C1_kl3_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_BOOLEAN F4_1279(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F4_1280(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F4_1281(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F4_1282(EIF_REFERENCE, EIF_REFERENCE);
extern void EIF_Minit3(void);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1041_9333(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
