
#ifndef _C1_pa4_
#define _C1_pa4_

#ifdef __cplusplus
extern "C" {
#endif

extern void F7_1296(EIF_REFERENCE, EIF_INTEGER_32);
extern void F7_1297(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F7_1298(EIF_REFERENCE);
extern EIF_CHARACTER_8 F7_1299(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_CHARACTER_8 F7_1300(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_BOOLEAN F7_1301(EIF_REFERENCE, EIF_INTEGER_32);
extern void F7_1302(EIF_REFERENCE, EIF_CHARACTER_8, EIF_INTEGER_32);
extern EIF_BOOLEAN F7_1303(EIF_REFERENCE, EIF_REFERENCE);
extern void F7_1304(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_1305(EIF_REFERENCE);
extern void F7_1(EIF_REFERENCE, int);
extern void EIF_Minit4(void);
extern EIF_BOOLEAN F1_9(EIF_REFERENCE, EIF_REFERENCE);
extern void F234_4723(EIF_REFERENCE, EIF_INTEGER_32);
extern void F234_4758(EIF_REFERENCE, EIF_INTEGER_8, EIF_INTEGER_32);
extern EIF_BOOLEAN F234_4732(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_8 F234_4738(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
