
#ifndef _C1_so43_
#define _C1_so43_

#ifdef __cplusplus
extern "C" {
#endif

extern void F63_2161(EIF_REFERENCE);
extern void F63_2162(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F63_2163(EIF_REFERENCE);
extern EIF_INTEGER_32 F63_2164(EIF_REFERENCE);
extern EIF_BOOLEAN F63_2165(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F63_2166(EIF_REFERENCE);
extern void F63_2167(EIF_REFERENCE, EIF_INTEGER_32);
extern void F63_2168(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F63_2169(EIF_REFERENCE);extern EIF_INTEGER_32 address_size();

extern void F63_2170(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);extern void set_sock_family(EIF_POINTER, EIF_INTEGER_32);

extern EIF_INTEGER_32 F63_2171(EIF_REFERENCE, EIF_POINTER);extern EIF_INTEGER_32 get_sock_family(EIF_POINTER);

extern void F63_2172(EIF_REFERENCE, EIF_POINTER, EIF_POINTER);extern void set_sock_data(EIF_POINTER, EIF_POINTER);

extern EIF_POINTER F63_2173(EIF_REFERENCE, EIF_POINTER);extern EIF_POINTER get_sock_data(EIF_POINTER);

extern void EIF_Minit43(void);
extern EIF_BOOLEAN F1_9(EIF_REFERENCE, EIF_REFERENCE);
extern void F234_4723(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_BOOLEAN F234_4732(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F1_7(EIF_REFERENCE, EIF_REFERENCE);
extern void F1_16(EIF_REFERENCE, EIF_REFERENCE);
extern void F234_4725(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);
extern char *(*R2159[])();
extern char *(*R2160[])();
extern char *(*R2161[])();

#ifdef __cplusplus
}
#endif

#endif
