/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F1026_8856();
extern void F1026_8860();
extern void F1030_9022();
extern void F1030_9027();
extern void F725_6454();
extern void F1017_8703();
extern void F179_3127();
extern EIF_REFERENCE F179_3114();
extern EIF_BOOLEAN F179_3126();
extern EIF_BOOLEAN F179_3134();
extern void F179_3136();
extern void F179_3137();
extern void F179_3138();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F1026_8856;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F1026_8860;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F1030_9022;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F1030_9027;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F725_6454;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F1017_8703;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F179_3127;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F179_3126;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F179_3114;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F179_3134;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F179_3136;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F179_3137;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F179_3138;

	egc_str_dtype = 1027;

	egc_immstr8_dtype = 1026;

	egc_str32_dtype = 1031;

	egc_immstr32_dtype = 1030;
	egc_arr_dtype = 724;
	egc_tup_dtype = 943;
	egc_disp_rout_id = 4345;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x034F;
	egc_sp_wchar = 0x034E;
	egc_sp_bool = 0x0355;
	egc_sp_uint8 = 0x0354;
	egc_sp_uint16 = 0x035B;
	egc_sp_uint32 = 0x0351;
	egc_sp_uint64 = 0x0353;
	egc_sp_int8 = 0x035A;
	egc_sp_int16 = 0x0359;
	egc_sp_int32 = 0x0352;
	egc_sp_int64 = 0x0350;
	egc_sp_real32 = 0x0357;
	egc_sp_real64 = 0x0358;
	egc_sp_pointer = 0x0356;
	egc_sp_ref = 0x034D;

	egc_uint8_dtype = 964;
	egc_uint16_dtype = 982;
	egc_uint32_dtype = 961;
	egc_uint64_dtype = 958;
	egc_int8_dtype = 955;
	egc_int16_dtype = 952;
	egc_int32_dtype = 949;
	egc_int64_dtype = 946;
	egc_bool_dtype = 979;
	egc_real32_dtype = 967;
	egc_char_dtype = 976;
	egc_wchar_dtype = 973;
	egc_real64_dtype = 970;
	egc_point_dtype = 1015;

	egc_exception_dtype = 138;
	egc_except_emnger_dtype = 178;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	exception_stack_managed = (EIF_BOOLEAN) 1;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "simple_github_runner";
	egc_system_location = "D:\\prod\\simple_github_runner\\EIFGENs\\simple_github_runner_tests\\F_code";
	egc_compiler_tag = 39;
	egc_project_version = 1769187835;
	egc_has_old_special_semantic = 0;
	scount = 1075;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "TEST_APP.make";
	egc_rcdt[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 49; /* TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 247; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 1072; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
